module.exports = {

    // API CHANNELS
    FETCH_DATA_FROM_STORAGE: 'fetch-data-from-storage',
    HANDLE_FETCH_DATA: 'handle-fetch-data',
    SAVE_DATA_TO_STORAGE: 'save-data-to-storage',
    HANDLE_SAVE_DATA: 'handle-save-data',
    SAVE_CANVAS_STATE: 'save-canvas-state',
    LOAD_CANVAS_STATE: 'load-canvas-state',
    UPDATE_PROJECT_FILE: 'set-project-file',
    GET_PROJECT_FILE: 'get-project-file',
    GET_ATOMS: 'get-atoms',
    GET_PROJECTS: 'get-projects',
    OPEN_PROJECT: 'open-project',
    GET_TESTS: 'get-tests',
    SELECT_FILE: 'select-file',
    CREATE_NEW_PROJECT: 'create-new-project',
    GET_HOME_DIRECTORY: 'get-home-directory',
    CREATE_NEW_TEST: 'create-new-test',
    SET_ATOM_COLOR: 'set-atom-color',
    GET_ATOM_COLOR: 'get-atom-color',
    SET_ATOM_LABEL: 'set-atom-label',
    GET_ATOM_LABEL: 'get-atom-label',
    GET_ACCEPT_TYPES: 'get-accept-types',
    GET_ATOM_MULTIPLICITY: 'get-atom-multiplicity',
    GET_RELATIONS: 'get-relations',
    DELETE_ATOM: 'delete-atom',
    GET_CONNECTIONS: 'get-connection',
    MAKE_CONNECTION: 'make-connection',
    DELETE_CONNECTION: 'delete-connection',
    RUN_TEST: 'convert-to-command-string',
    GET_PROJECT_TABS: 'get-project-tabs',
    SET_PROJECT_TABS: 'set-project-tabs',
    OPEN_AND_SET_ACTIVE: 'open-and-set-active',
    SET_ACTIVE_TAB: 'set-active-tab',
    CLOSE_TAB: 'close-tab',
    DELETE_TEST: 'delete-test',
    CREATE_ATOM: 'create-atom',
    // UI VARIABLES
    SIDEBAR_WIDTH: 500,

    // ITEM TYPES
    ATOM: 'Atom',
    ATOM_SOURCE: 'AtomSource',
    CONNECTION: 'Connection'
}