module.exports = {
    FETCH_DATA_FROM_STORAGE: 'fetch-data-from-storage',
    HANDLE_FETCH_DATA: 'handle-fetch-data',
    SAVE_DATA_TO_STORAGE: 'save-data-to-storage',
    HANDLE_SAVE_DATA: 'handle-save-data',
    SAVE_CANVAS_STATE: 'save-canvas-state',
    LOAD_CANVAS_STATE: 'load-canvas-state',
    UPDATE_PROJECT_FILE: 'set-project-file',
    GET_PROJECT_FILE: 'get-project-file',
    GET_ATOMS: 'get-atoms',
    GET_PROJECTS: 'get-projects',
    OPEN_PROJECT: 'open-project',
    GET_TESTS: 'get-tests',
    SELECT_FILE: 'select-file',
    CREATE_NEW_PROJECT: 'create-new-project',
    GET_HOME_DIRECTORY: 'get-home-directory',
}